trigger:
- RK-PowerBi-Deployment

parameters:
- name: ServiceConn
  displayName: ServiceConn
  type: string
  default: PROD-Connection2
- name: PowerBiServiceConn
  displayName: PowerBiServiceConn
  type: string
  default: Power-bi conn
- name: groupvariables
  type: object
  default:
   - CloudMonitorSentis


stages:

- stage: 'DeployDB'
  displayName: 'Deploy to SQL Database'
  pool:
    name: DevOpsBuildAgentProdWindowsPool
  jobs:
  - ${{ each group in parameters.groupvariables }}:
      - job:
        displayName: 'Deploy to SQL Database'
        variables:
        - name: sdkVersion
          value: initialValue 
        steps:
        
        
        - task: AzurePowerShell@5
          displayName: 'Update credentials'
          inputs:
            azureSubscription: '${{ parameters.ServiceConn }}'
            ScriptType: 'FilePath'
            ScriptPath: '$(System.DefaultWorkingDirectory)\Refresh Script\test.ps1'
            ScriptArguments: ''
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
        - task: CmdLine@2
          inputs:
            script: |
              echo ${{ variables.sdkVersion }}
              echo Hello world
