trigger:
- RK-PowerBi-Deployment

parameters:
- name: ServiceConn
  displayName: ServiceConn
  type: string
  default: PROD-Connection2
- name: PowerBiServiceConn
  displayName: PowerBiServiceConn
  type: string
  default: Power-bi conn
- name: groupvariables
  type: object
  default:
   - CloudMonitorSentis


stages:

- stage: 'DeployDB'
  displayName: 'Deploy to SQL Database'
  pool:
    name: DevOpsBuildAgentProdWindowsPool
  jobs:
  - ${{ each group in parameters.groupvariables }}:
      - job:
        displayName: 'Deploy to SQL Database'
        variables:
        
        - group: Release for Foundation Function Apps ${{ group }}
        - name: BiId
          value: ${{ variables.PowerBiClientId }}
        - name: BiKey
          value: ${{ variables.PowerBiClientSecretKey }}
        
        steps:
            - task: PowerBIToolInstaller@1
            
            - task: AzurePowerShell@5
              name: Updatecredentials
              inputs:
                azureSubscription: '${{ parameters.ServiceConn }}'
                ScriptType: 'InlineScript'
                Inline: |
                  $clientsec =  ConvertTo-SecureString -String $env:PowerBiClientSecretKey -AsPlainText -Force

                  $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $env:PowerBiClientId, $clientsec

                  Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId "$env:TENANTIDDD"

                  $workspace = Get-PowerBIWorkspace -Filter "name eq 'Test'"

                  if ($workspace -ne $null){
                  $workspace_id = $workspace.Id
                  Write-Host "##vso[task.setvariable variable=BiId]"$workspace.Id""
                  Write-Host "Workspace: yes $($workspace_id)"
                  }
                  else{
                  New-PowerBIWorkspace -Name 'Test'
                  Add-PowerBIWorkspaceUser -Id '7638c835-dbd4-49e4-ad77-3f890758f7f5' -UserEmailAddress rohith.korupalli@data-driven.com -AccessRight Admin
                  }
                    
                  write-Host "$env:PowerBiClientId"
                  Write-Host "##vso[task.setvariable variable=BiId]"$workspace.Id""
                  
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true
            - task: PowerBIImport@1
              inputs:
                connection: 'PowerBi-refreshConn'
                workspace: '$(BiId)'
                path: '$(System.DefaultWorkingDirectory)\Power BI\CloudMonitor.pbix'
            - task: AzurePowerShell@5
              name: Updatecredentials2
              inputs:
                azureSubscription: '${{ parameters.ServiceConn }}'
                ScriptType: 'InlineScript'
                Inline: |
                   Write-Host "Variable : $(BiId)"
                  
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true
            