trigger:
- RK-PowerBi-Deployment

parameters:
- name: ServiceConn
  displayName: ServiceConn
  type: string
  default: PROD-Connection2
- name: PowerBiServiceConn
  displayName: PowerBiServiceConn
  type: string
  default: Power-bi conn
- name: groupvariables
  type: object
  default:
   - CloudMonitorSentis


stages:

- stage: 'DeployDB'
  displayName: 'Deploy to SQL Database'
  pool:
    name: DevOpsBuildAgentProdWindowsPool
  jobs:
  - ${{ each group in parameters.groupvariables }}:
      - job:
        displayName: 'Deploy to SQL Database'
        variables:
        
        - group: Release for Foundation Function Apps ${{ group }}
        - name: sdkVersion
          value: initialValue
        - name: BiId
          value: ${{ variables.PowerBiClientId }}
        - name: BiKey
          value: ${{ variables.PowerBiClientSecretKey }}
        
        steps:
        
            - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
              name: setvarStep
            - script: |
                echo $(setvarStep.myOutputVar)
                echo $env:BiId
              name: echovar
    
            - task: AzurePowerShell@5
              name: Updatecredentials
              inputs:
                azureSubscription: '${{ parameters.ServiceConn }}'
                ScriptType: 'InlineScript'
                Inline: |
                  Write-Host "##vso[task.setvariable variable=deployActivity]"Example string""
                  
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true
              
            - task: AzurePowerShell@5
              name: Updatecredentials2
              inputs:
                azureSubscription: '${{ parameters.ServiceConn }}'
                ScriptType: 'InlineScript'
                Inline: |
                   Write-Host "Deploy Activity: $(deployActivity)"
                  
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true
                
            - task: CmdLine@2
              inputs:
                script: |
                  echo $(Updatecredentials.sdkVersion)
                  echo Hello world
