trigger:
- dev

parameters:
- name: ServiceConn
  displayName: ServiceConn
  type: string
  default: PROD-Connection2
- name: PowerBiServiceConn
  displayName: PowerBiServiceConn
  type: string
  default: Power-bi conn
- name: groupvariables
  type: object
  default:
   - CloudMonitorDDProd

stages:

- stage: 'StartVM'
  displayName: 'ChecktostartVM'
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job:
    - group: DD Build Variables
    steps: 
    
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'InlineScript'
        Inline: |
          $clientsec =  ConvertTo-SecureString -String "$env:CLIENT_SECRET" -AsPlainText -Force

          $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "$env:CLIENT_ID", $clientsec

          Connect-AzAccount -ServicePrincipal -SubscriptionId "$env:SUBSCRIPTION_ID" -TenantId "$env:TENANT_ID" -Credential $credential

          set-AzContext -Subscription "$env:SUBSCRIPTION_ID" -Tenant "$env:TENANT_ID"
          
          $vmstatus = Get-AzVM -ResourceGroupName "DevOps-Build-Agents" -Name "DevOpsBuildAgentProdWindowsPoolVM" -Status
          
          if ($vmstatus.Statuses[1].Code -eq "PowerState/running")
          {
          Write-Host "Running"
          }
          else
          {
          Write-Host "Currently Stopped"
          Start-AzVM -ResourceGroupName "DevOps-Build-Agents" -Name "DevOpsBuildAgentProdWindowsPoolVM"
          }
        azurePowerShellVersion: 'LatestVersion'